"""add_full_name_to_users

Revision ID: 810de4eea248
Revises: eac8d99d29e5
Create Date: 2026-02-04 21:44:57.315705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '810de4eea248'
down_revision: Union[str, Sequence[str], None] = 'eac8d99d29e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True, comment='用户全名'))
    op.drop_index('email', table_name='users')
    op.drop_index('username', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'users', ['username'], unique=True)
    op.create_index('email', 'users', ['email'], unique=True)
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
